sonar.projectKey=mi-proyecto-gestion-sw
sonar.projectName=mi-proyecto-gestion-sw
sonar.sources=.
sonar.exclusions=node_modules/**,tests/**,coverage/**,.github/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
